#!/bin/bash
# run from terminal ./hide

echo "|--------------------------------------------------------------------|"
echo "|       This script will allow you to hide the data inside your      |"
echo "|   .MKV container. Please follow the instructions below to launch   |"
echo "|                 data_hiding process successfully.                  |"
echo "|--------------------------------------------------------------------|"
read -p "  Enter the name of your .MKV container and press [ENTER]: " filename

if [ "${filename: -4}" == ".mkv" ]; then
	cat ${filename} | python parse_and_convert_mkv2xml.py > .tmp.xml && 
	python hide_data.py .tmp.xml &&
	cat .hidden_data.xml | python convert_xml2mkv.py > modified_mkv.mkv &&
	rm .tmp.xml && rm .hidden_data.xml
else
	echo "|--------------------------------------------------------------------|"
	echo "|  The file that you are trying to select is not .MKV container.     |"
	echo "|           Relaunch the script with .MKV extension.                 |"
	echo "|--------------------------------------------------------------------|"
fi
